from typing import TypedDict, List, Dict, Any, Optional


class ResearchState(TypedDict):
    """
    Central shared memory for the Supervisor-driven multi-agent research workflow,
    including fields for quality evaluation and refinement loops.
    """

    # --- User Inputs & Planning ---
    user_query: str                     # Original query from the user
    semantic_query: str                 # Processed / cleaned / normalized user query, CleanQueryAgent (procedural_agents.py)
    primary_intent: str                 # Classified intent (e.g., material, disease), Intent Agent (planning_agents.py)
    reasoning: str                      # <--- FIXED: Added for Intent justification
    execution_plan: List[str]           # High-level plan generated by LLM, Planning Agent (planning_agents.py)

    # --- CRITICAL FIX: NEW KEY FOR STABLE CONSTRAINTS ---
    system_constraints: List[str]       # Stable, structured constraints (e.g., ['TIME_PERIOD: last_decade', 'TOPIC: Quantum']), set by IntentAgent.

    # --- MERGED KEY (Constraints + Elements) ---
    # This list will be the MERGED output (Constraints + Chemical Formula/Elements).
    # Downstream agents (Arxiv, Materials) read from this list for compatibility.
    material_elements: List[str]        # MERGED: All structured constraints AND extracted elements (e.g., ['TIME_PERIOD: last_decade', 'CsSnI3', 'Cs', 'Sn']), updated by QueryGenerationAgent.
    api_search_term: str                # Specific term used for MP search (e.g., LiCoO2), QueryGenerationAgent (planning_agents.py)
    tiered_queries: Dict[str, Dict[str, str]]   # strict/moderate/broad queries for each tool, QueryGenerationAgent (planning_agents.py)
    active_tools: List[str]             # Tools selected by the, Planning Agent (planning_agents.py)

    # --- Tool and Retrieval Data ---
    raw_tool_data: List[Dict[str, Any]]    # All raw outputs from all tool agents (abstracts, web snippets, etc.) (tool_agents.py)
    references: List[str]               # Citations gathered during the (tool_agents.py)

    # --- RAG & Control Flags ---
    full_text_chunks: List[Dict[str, Any]] # Extracted + smart-chunked PDF content (rag_agents.py)
    rag_complete: Optional[bool]        # Signals that the RAG pipeline has finished executing. (rag_agents.py)
    is_refining: bool                   # Set to True when looping back from evaluation (rag_agents.py)
    filtered_context: str               # Semantic + keyword-filtered context ready for synthesis (rag_agents.py)


    # --- Finalization & Evaluation Loop ---
    final_report: str                   # The comprehensive report produced by the synthesis agent
    report_generated: bool              # Flag set by SynthesisAgent
    needs_refinement: bool              # CRITICAL FLAG: Set by EvaluationAgent.
    refinement_reason: str              # Feedback from the Evaluation LLM.

    # Track how many times we have looped back
    refinement_retries: int

    # Internal routing/control fields
    next: str                           # Key used by the graph to determine the next node or 'TERMINATE'

    # Used for tracking the sequential visited agent
    visited_nodes: List[str]  # Use 'add' to accumulate the path