import sys
import os
import pytest
import asyncio
import re

# 1. PATH SETUP: This allows the test to "see" inside the backend folder
root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
backend_dir = os.path.join(root_dir, 'backend')

if root_dir not in sys.path:
    sys.path.append(root_dir)
if backend_dir not in sys.path:
    sys.path.append(backend_dir)

# 2. IMPORT: Now we import from the backend package
from backend.main import initialize_research_session, run_research_query

@pytest.mark.asyncio
async def test_research_integrity_locally():
    """
    Local Validation: Ensures the LangGraph logic executes and
    returns a state with verifiable references safely.
    """
    print(f"\n--- Initializing Local Research Session ---")

    # Initialize using your main.py logic
    system = initialize_research_session()

    # Test Query (Use a specific one to ensure RAG triggers)
    query = "Thermal stability of CsPbI3 perovskites."

    # Execute the query headlessly
    final_state = await asyncio.to_thread(run_research_query, system, query)

    # Ensure final_state is a dictionary
    if not isinstance(final_state, dict):
        final_state = {"final_report": str(final_state)}

    # --- LLMOps VALIDATION GATES ---

    # Gate 1: Report Generation
    final_report = final_state.get("final_report", "")
    assert final_report and len(final_report) > 50, "❌ Error: Final report missing or too short."

    # Gate 2: Evidence Grounding
    references = final_state.get("references", [])
    assert isinstance(references, list), "❌ Error: References must be a list."
    assert len(references) > 0, "❌ Error: No citations found. The AI might be hallucinating."

    # Gate 3: Logic Path Verification
    visited_nodes = final_state.get("visited_nodes", [])
    assert len(visited_nodes) > 2, "❌ Error: Graph reached END too quickly. Agents were bypassed."

    print(f"\n✅ Local Test Passed: AI reasoning is grounded and traceable.")

    # --- ADVANCED LLMOps GATES ---

    # Gate 4: Citation Integrity (Anti-Hallucination Check)
    report_citations = re.findall(r'\[(\d+)\]', final_report)
    report_citations = set(map(int, report_citations))
    num_references_provided = len(references)

    assert len(report_citations) > 0, "❌ LLMOps Alert: Report generated without any citations."

    for cite_num in report_citations:
        assert cite_num <= num_references_provided, \
            f"❌ Hallucination Detected: Report cites [{cite_num}], but only {num_references_provided} references exist."

    # Gate 5: RAG Efficiency Check
    raw_tool_data = final_state.get("raw_tool_data", [])
    raw_data_count = len(raw_tool_data)

    if raw_data_count > 0:
        utilization_ratio = num_references_provided / raw_data_count
        print(f"📊 RAG Utilization: {utilization_ratio:.2%}")

    print("\n" + "="*50)
    print("FINAL REPORT GENERATED BY AGENT:")
    print("="*50)
    print(final_report)
    print("="*50)