import sys
import os
import pytest
import asyncio

# 1. PATH SETUP: This allows the test to "see" inside the backend folder
# We add both the root and the backend directory to sys.path
root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
backend_dir = os.path.join(root_dir, 'backend')

if root_dir not in sys.path:
    sys.path.append(root_dir)
if backend_dir not in sys.path:
    sys.path.append(backend_dir)

# 2. IMPORT: Now we import from the backend package
from backend.main import initialize_research_session, run_research_query

@pytest.mark.asyncio
async def test_research_integrity_locally():
    """
    Local Validation: Ensures the LangGraph logic executes and
    returns a state with verifiable references.
    """
    print(f"\n--- Initializing Local Research Session ---")

    # Initialize using your main.py logic
    system = initialize_research_session()

    # Test Query (Use a specific one to ensure RAG triggers)
    query = "Thermal stability of CsPbI3 perovskites."

    # Execute the query headlessly (mimicking your main.py flow)
    # We use to_thread because your run_research_query is synchronous
    final_state = await asyncio.to_thread(run_research_query, system, query)

    # --- LLMOps VALIDATION GATES ---

    # Gate 1: Report Generation
    assert "final_report" in final_state, "❌ Error: Final report missing from state."
    assert len(final_state["final_report"]) > 50, "❌ Error: Report is too short or empty."

    # Gate 2: Evidence Grounding (CRITICAL for Sunhat)
    assert "references" in final_state, "❌ Error: References key missing from state."
    assert len(final_state["references"]) > 0, "❌ Error: No citations found. The AI might be hallucinating."

    # Gate 3: Logic Path Verification
    assert "visited_nodes" in final_state, "❌ Error: Traceability data missing."
    assert len(final_state["visited_nodes"]) > 2, "❌ Error: Graph reached END too quickly. Agents were bypassed."

    print(f"\n✅ Local Test Passed: AI reasoning is grounded and traceable.")

    # --- ADVANCED LLMOps GATES ---

    # --- REFINED LLMOps GATES ---

    # Gate 4: Citation Integrity (The 'Anti-Hallucination' Check)
    # 1. Extract all [Number] citations from the report text
    import re
    report_citations = re.findall(r'\[(\d+)\]', final_state["final_report"])
    report_citations = set(map(int, report_citations))

    # 2. Get the list of references actually provided at the bottom of the report
    # (Assuming your state stores the final reference list used by the Synthesis Agent)
    num_references_provided = len(final_state.get("references", []))

    # ASSERT: The report must have at least ONE citation (it shouldn't be empty)
    assert len(report_citations) > 0, "❌ LLMOps Alert: Report generated without any citations."

    # ASSERT: The AI must not "hallucinate" a reference number that isn't in the reference list
    for cite_num in report_citations:
        assert cite_num <= num_references_provided, \
            f"❌ Hallucination Detected: Report cites [{cite_num}], but only {num_references_provided} references exist."

    # Gate 5: RAG Efficiency Check
    # We expect some filtering! If 100% of raw data is used, the RAG might be too loose.
    # If 0% is used, the RAG is too tight.
    raw_data_count = len(final_state.get("raw_tool_data", []))
    used_ref_count = len(final_state.get("references", []))

    if raw_data_count > 0:
        utilization_ratio = used_ref_count / raw_data_count
        print(f"📊 RAG Utilization: {utilization_ratio:.2%}")
        # We just log this for the CI/CD artifacts to show 'Precision'

    # ... ................................................
    print("\n" + "="*50)
    print("FINAL REPORT GENERATED BY AGENT:")
    print("="*50)
    print(final_state.get("final_report"))
    print("="*50)